title: Nathan Cahn  # your name (or website title) here
logo: "/images/darth_vader_logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Linguist by training and data scientist in the making
  <br><br>
  <a href="https://www.linkedin.com/in/nathan-cahn-900b63a1/" target="_blank">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
